name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Rename jar to vowbot.jar
        run: |
          find build/libs -name "*-all.jar" -type f -exec cp {} vowbot.jar \;

      - name: Copy Dockerfile
        run: cp Dockerfile dockerfile

      - name: Upload jar and Dockerfile artifact
        uses: actions/upload-artifact@v4
        with:
          name: vowbot-artifact
          path: |
            vowbot.jar
            dockerfile

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download jar and Dockerfile artifact
        uses: actions/download-artifact@v4
        with:
          name: vowbot-artifact

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.ORACLE_CLOUD_SSH_PRIVATE_KEY }}

      - name: Transfer files to server
        run: |
          scp -o StrictHostKeyChecking=no vowbot.jar dockerfile ubuntu@${{ secrets.SERVER_IP }}:bot/

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} '
            cd bot
            docker ps -q --filter "name=vowbot" | xargs -r docker stop
            docker ps -aq --filter "name=vowbot" | xargs -r docker rm
            docker build -t vowbot:latest .
            docker run -d --name vowbot --restart unless-stopped vowbot:latest
            docker image prune -f
          '